import React,{useEffect,useMemo,useState}from'react';
import{useLocation,useNavigate}from'react-router-dom';
import{supabase}from'./lib/supabase.js';
import{adminPublishResult,adminIssueCertificate,downloadSubmission,markNotificationRead}from'./lib/api.js';

const fmt=d=>d?new Date(d).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'}):'—';
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n)||0);
const safe=async(q,fallback=[])=>{try{const{data,error}=await q;if(error)throw error;return data||fallback}catch{return fallback}};
const pages=[
 ['overview','speedometer2','Overview'],['students','people','Students'],['enrollments','person-check','Enrollments'],['assignments','inbox','Assignments'],['courses','book','Courses'],['instructors','person-badge','Instructors'],['complaints','chat-square-text','Complaints'],['activity','activity','Activity log'],['notifications','bell','Notifications'],['sales','graph-up-arrow','Sales & codes'],['admins','shield-lock','Admins'],['profile','person-circle','My profile']
];

function AdminNav({page,setPage}){
 return <aside className="admin-shell-nav"><div className="admin-brand"><span>TAMP</span><i>.</i><small>CONTROL CENTER</small></div><div className="admin-nav-group">{pages.map(([id,ic,label])=><button key={id} className={page===id?'on':''} onClick={()=>setPage(id)}><i className={'bi bi-'+ic}/><span>{label}</span>{page===id&&<b><i className="bi bi-chevron-right"/></b>}</button>)}</div><div className="admin-nav-foot"><button onClick={()=>setPage('profile')}><i className="bi bi-person-circle"/> Owner profile</button><a href="/"><i className="bi bi-box-arrow-up-right"/> Open campus</a></div></aside>
}

function Metric({icon,label,value,meta}){return <article className="admin-metric"><span><i className={'bi bi-'+icon}/></span><small>{label}</small><strong>{value}</strong>{meta&&<em>{meta}</em>}</article>}
function Empty({icon='inbox',title,body}){return <div className="admin-empty"><i className={'bi bi-'+icon}/><h3>{title}</h3><p>{body}</p></div>}
function SectionHead({eyebrow,title,body,action}){return <div className="admin-section-head"><div><span>{eyebrow}</span><h2>{title}</h2>{body&&<p>{body}</p>}</div>{action}</div>}

function Overview({data,onRefresh}){
 const countries=useMemo(()=>{const m={};for(const s of data.students){const c=s.country||'Unknown';m[c]=(m[c]||0)+1}return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,8)},[data.students]);
 const activity=[...data.events].slice(0,8);
 return <div className="admin-page-view"><div className="admin-page-title"><div><span>PLATFORM OVERVIEW</span><h1>Good to see you, Owner.</h1><p>One operational view of TAMP — learners, cohort activity, academic work and business signals.</p></div><button className="admin-icon-btn" onClick={onRefresh}><i className="bi bi-arrow-clockwise"/></button></div>
 <div className="admin-metrics"><Metric icon="people" label="Students" value={data.students.length}/><Metric icon="person-check" label="Active enrollments" value={data.enrollments.filter(x=>x.status==='active').length}/><Metric icon="inbox" label="Pending work" value={data.submissions.filter(x=>x.status!=='published').length}/><Metric icon="cash-stack" label="Recorded sales" value={money(data.sales)}/><Metric icon="key" label="Enrollment codes" value={data.keys.length}/><Metric icon="patch-check" label="Certificates" value={data.certificates.length}/></div>
 <div className="admin-overview-grid"><section className="admin-panel admin-map-panel"><SectionHead eyebrow="LEARNER MAP" title="Where TAMP is reaching" body="A live cohort geography view built from student profiles."/><div className="admin-map"><div className="map-grid">{Array.from({length:42},(_,i)=><i key={i} className={i%7===0||i%11===0?'hot':''}/>)}</div><div className="map-labels">{countries.length?countries.map(([c,n])=><span key={c}><b>{c}</b><strong>{n}</strong></span>):<span><b>No location data yet</b><strong>0</strong></span>}</div></div></section>
 <section className="admin-panel"><SectionHead eyebrow="RECENT ACTIVITY" title="What is happening now"/>{activity.length?activity.map(x=><div className="admin-activity-row" key={x.id||Math.random()}><span><i className="bi bi-activity"/></span><div><b>{x.action||x.event_type||'Platform activity'}</b><small>{x.summary||x.message||'Activity recorded'}</small></div><time>{fmt(x.created_at)}</time></div>):<Empty icon="activity" title="No activity yet" body="Student and platform events will appear here."/>}</section></div>
 <div className="admin-overview-grid"><section className="admin-panel"><SectionHead eyebrow="COHORT" title="October 26, 2026"/><div className="admin-cohort-line"><b>Data Analysis</b><span>Beginner friendly</span><span>₦2,000</span><span>{data.enrollments.length} registrations</span></div><div className="admin-progress"><i style={{width:Math.min(100,data.enrollments.length/20*100)+'%'}}/></div></section><section className="admin-panel"><SectionHead eyebrow="QUICK ACTIONS" title="Operate TAMP"/><div className="admin-quick-actions">{[['students','people','Review students'],['assignments','inbox','Grade submissions'],['courses','book','Manage courses'],['complaints','chat-square-text','Handle complaints']].map(([p,i,l])=><button key={p} onClick={()=>location.hash=p}><i className={'bi bi-'+i}/>{l}</button>)}</div></section></div>
 </div>
}

function Students({data}){
 const[q,setQ]=useState('');const rows=data.students.filter(s=>(s.full_name+' '+s.email+' '+s.student_id+' '+s.country).toLowerCase().includes(q.toLowerCase()));
 return <div className="admin-page-view"><div className="admin-page-title"><div><span>STUDENTS</span><h1>Every learner, clearly.</h1><p>Search student identity, contact, education and cohort status from one workspace.</p></div></div><div className="admin-toolbar"><div className="admin-search"><i className="bi bi-search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email, student ID…"/></div><span>{rows.length} records</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Contact</th><th>Location</th><th>Education</th><th>Joined</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>{s.full_name||'Unnamed student'}</b><small>{s.student_id||'No student ID'}</small></td><td><b>{s.email||'—'}</b><small>{s.phone||'—'}</small></td><td>{s.city||'—'}{s.country?<small>{s.country}</small>:null}</td><td>{s.education_level||'—'}<small>{s.institution||'—'}</small></td><td>{fmt(s.created_at)}</td></tr>)}</tbody></table>{!rows.length&&<Empty title="No students found" body="Try a different search."/>}</div></div>
}

function Enrollments({data}){return <div className="admin-page-view"><div className="admin-page-title"><div><span>ENROLLMENTS</span><h1>Cohort registrations.</h1><p>See who registered, how access was granted and when learning becomes available.</p></div></div><div className="admin-card-grid">{data.enrollments.map(x=><article className="admin-record-card" key={x.id}><div className="record-icon"><i className="bi bi-person-check"/></div><div><span className="admin-status">{x.status||'unknown'}</span><h3>{x.profiles?.full_name||x.student_name||'Student'}</h3><p>{x.profiles?.email||x.email||'Email unavailable'}</p><small>{x.profiles?.student_id||'No ID'} · {x.profiles?.country||'Country unavailable'}</small></div><time>{fmt(x.created_at)}</time>{x.unlock_at&&<div className="record-foot">Access unlock: {fmt(x.unlock_at)}</div>}</article>)}</div>{!data.enrollments.length&&<Empty icon="person-check" title="No enrollments yet" body="New cohort registrations will appear here."/>}</div>}

function Assignments({data}){const[filter,setFilter]=useState('pending');const rows=data.submissions.filter(x=>filter==='all'||(filter==='pending'?x.status!=='published':x.status==='published'));const grade=async(x)=>{const score=Number(document.getElementById('a-score-'+x.id)?.value||0);const feedback=document.getElementById('a-feedback-'+x.id)?.value||'';try{await adminPublishResult({submissionId:x.id,score,feedback});alert('Assessment published.')}catch(e){alert(e.message)}};return <div className="admin-page-view"><div className="admin-page-title"><div><span>ACADEMIC WORK</span><h1>Assignments to review.</h1><p>Only submitted work tied to the active curriculum is shown. Grade, comment and issue certificates from here.</p></div></div><div className="admin-segment">{[['pending','Needs review'],['published','Published'],['all','All']].map(([v,l])=><button key={v} className={filter===v?'on':''} onClick={()=>setFilter(v)}>{l}</button>)}</div><div className="admin-assignment-list">{rows.map(x=><article className="admin-assignment" key={x.id}><div className="assignment-ident"><span className="record-icon"><i className="bi bi-file-earmark-text"/></span><div><span>{x.assignments?.course_id?'DATA ANALYSIS':'COURSE'}</span><h3>{x.assignments?.title||'Assignment submission'}</h3><p>{x.profiles?.full_name||'Student'} · {x.profiles?.student_id||'No ID'} · Submitted {fmt(x.submitted_at||x.created_at)}</p></div><span className="admin-status">{x.status}</span></div><div className="submission-body">{x.text_content&&<div><b>Written response</b><p>{x.text_content}</p></div>}{x.submission_url&&<a className="admin-link" href={x.submission_url} target="_blank" rel="noreferrer"><i className="bi bi-link-45deg"/> Open project</a>}{x.file_path&&<button className="admin-link" onClick={async()=>window.open(await downloadSubmission(x.file_path),'_blank')}><i className="bi bi-download"/> Open uploaded file</button>}</div>{x.status!=='published'&&<div className="grade-box"><div><label>Score / 100</label><input id={'a-score-'+x.id} type="number" min="0" max="100" defaultValue="0"/></div><div><label>Feedback</label><textarea id={'a-feedback-'+x.id} placeholder="What should the student know about this work?"/></div><div className="grade-actions"><button className="btn" onClick={()=>grade(x)}>Publish grade</button><button className="btn o" onClick={async()=>{try{const r=await adminIssueCertificate(x.id);alert('Certificate issued: '+r.certificate_id)}catch(e){alert(e.message)}}}>Issue certificate</button></div></div>}</article>)}</div>{!rows.length&&<Empty icon="inbox" title="Nothing to review" body="When students submit eligible work, it will appear here."/>}</div>}

function Courses({data}){const[c,setC]=useState(data.courses[0]||null),[editing,setEditing]=useState(false);const save=async()=>{if(!c)return;const{error}=await supabase.from('courses').update({title:c.title,description:c.description,start_date:c.start_date,duration_weeks:Number(c.duration_weeks||1)}).eq('id',c.id);if(error)alert(error.message);else{setEditing(false);alert('Course saved.')}};return <div className="admin-page-view"><div className="admin-page-title"><div><span>COURSES</span><h1>Course operations.</h1><p>Control public course information, cohort timing, fees and the curriculum path.</p></div><button className="btn" onClick={()=>setEditing(v=>!v)}>{editing?'Close editor':'Edit course'}</button></div>{c?<div className="admin-course-editor"><div className="admin-panel course-main-editor"><span className="admin-status">CURRENT COHORT</span><h2>{editing?<input value={c.title} onChange={e=>setC({...c,title:e.target.value})}/>:c.title}</h2>{editing?<textarea value={c.description||''} onChange={e=>setC({...c,description:e.target.value})}/>:<p>{c.description}</p>}<div className="admin-form-grid"><label>Start date<input type="date" value={c.start_date||''} onChange={e=>setC({...c,start_date:e.target.value})} disabled={!editing}/></label><label>Duration<input type="number" value={c.duration_weeks||1} onChange={e=>setC({...c,duration_weeks:e.target.value})} disabled={!editing}/></label></div>{editing&&<button className="btn" onClick={save}>Save course</button>}</div><div className="admin-panel"><SectionHead eyebrow="CURRICULUM" title="Learning phases"/>{data.levels.map(l=><div className="admin-curriculum-row" key={l.id}><span>{String(l.journey_number||l.level_number).padStart(2,'0')}</span><div><b>{l.title}</b><small>{l.description}</small></div><i className="bi bi-chevron-right"/></div>)}</div></div>:<Empty icon="book" title="No course found" body="Create or connect the current course in Supabase."/>}</div>}

function Instructors({data}){const[email,setEmail]=useState(''),[busy,setBusy]=useState(false);const assign=async()=>{setBusy(true);try{const{error}=await supabase.rpc('admin_set_course_instructor',{p_email:email.trim(),p_course_id:'da',p_active:true});if(error)throw error;alert('Instructor access granted.')}catch(e){alert(e.message)}finally{setBusy(false)}};return <div className="admin-page-view"><div className="admin-page-title"><div><span>INSTRUCTORS</span><h1>Academic team.</h1><p>Give trusted accounts access to Instructor Studio without exposing private administration controls.</p></div></div><div className="admin-panel"><SectionHead eyebrow="ACCESS CONTROL" title="Assign an instructor"/><div className="admin-form-inline"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="instructor@example.com"/><button className="btn" disabled={!email.trim()||busy} onClick={assign}>{busy?'Assigning…':'Grant access'}</button></div></div><div className="admin-card-grid">{data.instructors.map(x=><article className="admin-record-card" key={x.id}><div className="record-icon"><i className="bi bi-person-badge"/></div><div><span className="admin-status">INSTRUCTOR</span><h3>{x.full_name||'Instructor'}</h3><p>{x.email}</p><small>{fmt(x.created_at)}</small></div></article>)}</div></div>}

function Complaints({data}){const[reply,setReply]=useState({});const send=async(x)=>{if(!reply[x.id]?.trim())return;try{const{error}=await supabase.rpc('admin_reply_complaint',{p_complaint_id:x.id,p_reply:reply[x.id].trim()});if(error)throw error;setReply(v=>({...v,[x.id]:''}));alert('Reply sent and notification queued.')}catch(e){alert(e.message)}};return <div className="admin-page-view"><div className="admin-page-title"><div><span>SUPPORT & COMPLAINTS</span><h1>Listen and resolve.</h1><p>Student complaints, guidance requests and support cases should never disappear into a chat thread.</p></div></div><div className="admin-card-grid">{data.complaints.map(x=><article className="admin-record-card complaint-card" key={x.id}><div><span className="admin-status">{x.status||'open'}</span><h3>{x.subject||'Student complaint'}</h3><p>{x.message}</p><small>{x.email||x.profiles?.email||'Student'} · {fmt(x.created_at)}</small></div><textarea value={reply[x.id]||''} onChange={e=>setReply(v=>({...v,[x.id]:e.target.value}))} placeholder="Write a reply the student can receive as a notification…"/><button className="btn" onClick={()=>send(x)}>Reply & notify</button></article>)}</div>{!data.complaints.length&&<Empty icon="chat-square-text" title="No open complaints" body="Support cases will appear here when students submit them."/>}</div>}

function Activity({data}){return <div className="admin-page-view"><div className="admin-page-title"><div><span>AUDIT & ACTIVITY</span><h1>Everything worth knowing.</h1><p>Authentication, enrollment, assessment, certificate verification and support events are recorded for operations.</p></div></div><div className="admin-timeline">{data.events.map(x=><article key={x.id||Math.random()}><span><i className="bi bi-dot"/></span><div><b>{x.action||x.event_type||'Activity'}</b><p>{x.summary||x.message||JSON.stringify(x.metadata||{})}</p><small>{fmt(x.created_at)} · {x.actor_email||x.email||'System'}</small></div></article>)}</div>{!data.events.length&&<Empty icon="activity" title="No tracked events yet" body="Once event tracking is enabled, this timeline becomes your operational audit trail."/>}</div>}

function NotificationsPage({data}){return <div className="admin-page-view"><div className="admin-page-title"><div><span>NOTIFICATIONS</span><h1>Stay ahead of activity.</h1><p>Registration, login, course completion, certificate verification and complaint events should surface here.</p></div></div><div className="admin-notif-list">{data.notifications.map(x=><article key={x.id}><span><i className="bi bi-bell-fill"/></span><div><b>{x.title}</b><p>{x.message||x.body}</p><small>{fmt(x.created_at)}</small></div>{!x.read_at&&<button onClick={async()=>{await markNotificationRead(x.id)}}>Mark read</button>}</article>)}</div>{!data.notifications.length&&<Empty icon="bell" title="No notifications" body="New operational alerts will appear here."/>}</div>}

function Sales({data}){return <div className="admin-page-view"><div className="admin-page-title"><div><span>BUSINESS</span><h1>Sales & enrollment codes.</h1><p>See the commercial side of the cohort: recorded payments, generated codes and redeemed access.</p></div></div><div className="admin-metrics"><Metric icon="cash-stack" label="Recorded revenue" value={money(data.sales)}/><Metric icon="key" label="Codes generated" value={data.keys.length}/><Metric icon="key-fill" label="Codes redeemed" value={data.keys.filter(x=>x.redeemed_at).length}/><Metric icon="people" label="Paid/registered learners" value={data.enrollments.length}/></div><div className="admin-panel"><SectionHead eyebrow="ENROLLMENT CODES" title="Code ledger"/><div className="admin-code-list">{data.keys.map(k=><div key={k.id}><code>{k.code||'••••••••'}</code><span>{k.redeemed_at?'Redeemed':'Available'}</span><small>{fmt(k.created_at)}</small></div>)}</div></div></div>}

function Admins({profile}){const[email,setEmail]=useState(''),[permissions,setPermissions]=useState({overview:true,students:true,enrollments:true,assignments:true,courses:false,instructors:false,complaints:true,activity:true,notifications:true,sales:false}),[busy,setBusy]=useState(false);const add=async()=>{setBusy(true);try{const{error}=await supabase.rpc('admin_assign_admin',{p_email:email.trim(),p_permissions:permissions});if(error)throw error;alert('Admin assignment saved.');setEmail('')}catch(e){alert(e.message)}finally{setBusy(false)}};return <div className="admin-page-view"><div className="admin-page-title"><div><span>ADMINISTRATION</span><h1>Control who can operate TAMP.</h1><p>You remain the owner. Other administrators receive only the sections you explicitly grant.</p></div></div><div className="admin-panel"><SectionHead eyebrow="NEW ADMIN" title="Assign by email"/><div className="admin-form-inline"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com"/><button className="btn" disabled={!email.trim()||busy} onClick={add}>{busy?'Saving…':'Assign administrator'}</button></div><div className="permission-grid">{Object.keys(permissions).map(k=><label key={k}><input type="checkbox" checked={permissions[k]} onChange={e=>setPermissions(v=>({...v,[k]:e.target.checked}))}/><span>{k.replaceAll('_',' ')}</span></label>)}</div></div><div className="admin-panel"><SectionHead eyebrow="OWNER" title="Your authority"/><p className="admin-owner-note"><i className="bi bi-shield-check"/> {profile?.email||'Owner account'} is the platform owner. Owner-only actions remain outside delegated admin permissions.</p></div></div>}

function Profile({profile}){return <div className="admin-page-view"><div className="admin-page-title"><div><span>OWNER PROFILE</span><h1>Platform owner.</h1><p>This is an operational profile, not a student record. Grades and student academic controls do not belong here.</p></div></div><div className="admin-profile-grid"><div className="admin-panel owner-card"><div className="owner-avatar">{profile?.full_name?.[0]||'O'}</div><span className="admin-status">OWNER</span><h2>{profile?.full_name||'TAMP Owner'}</h2><p>{profile?.email||'Owner email'}</p><div className="owner-facts"><span>Platform access<strong>Full</strong></span><span>Academic record<strong>Not applicable</strong></span><span>Admin delegation<strong>Enabled</strong></span></div></div><div className="admin-panel"><SectionHead eyebrow="OWNER CONTROLS" title="What you can manage"/><div className="owner-control-list">{['Business performance and sales','Student records and cohort activity','Course and curriculum operations','Instructor access','Complaint resolution','Administrator permissions','Certificate verification activity'].map((x,i)=><div key={x}><i className="bi bi-check2"/><span>{x}</span></div>)}</div></div></div></div>}

export default function AdminCenter({profile}){
 const loc=useLocation(),nav=useNavigate(),initial=new URLSearchParams(loc.search).get('tab')||'overview';const[page,setPage]=useState(initial),[data,setData]=useState({students:[],enrollments:[],submissions:[],courses:[],levels:[],instructors:[],complaints:[],events:[],notifications:[],keys:[],certificates:[],sales:0}),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const[students,enrollments,submissions,courses,levels,instructors,complaints,events,notifications,keys,certificates,payments]=await Promise.all([
 safe(supabase.from('profiles').select('*').order('created_at',{ascending:false}),[]),
 safe(supabase.from('enrollments').select('*,profiles:user_id(full_name,email,student_id,country,phone)').eq('course_id','da').order('created_at',{ascending:false}),[]),
 safe(supabase.from('submissions').select('*,assignments(title,course_id,due_at),profiles:student_id(full_name,email,student_id)').order('submitted_at',{ascending:false}),[]),
 safe(supabase.from('courses').select('*').order('start_date'),[]),
 safe(supabase.from('course_levels').select('*').eq('course_id','da').order('level_number'),[]),
 safe(supabase.from('profiles').select('*').eq('role','instructor').order('created_at',{ascending:false}),[]),
 safe(supabase.from('student_complaints').select('*,profiles:user_id(full_name,email)').order('created_at',{ascending:false}),[]),
 safe(supabase.from('tamp_activity_events').select('*').order('created_at',{ascending:false}).limit(100),[]),
 safe(supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),[]),
 safe(supabase.from('enrollment_keys').select('*').eq('course_id','da').order('created_at',{ascending:false}).limit(200),[]),
 safe(supabase.from('certificates').select('*').eq('status','issued').order('issue_date',{ascending:false}),[]),
 safe(supabase.from('course_payments').select('amount,status').eq('status','paid'),[])
 ]);setData({students,enrollments,submissions,courses,levels,instructors,complaints,events,notifications,keys,certificates,sales:payments.reduce((a,x)=>a+Number(x.amount||0),0)});setLoading(false)};
 useEffect(()=>{if(profile?.role==='admin')load()},[profile?.role]);useEffect(()=>{if(initial)setPage(initial)},[loc.search]);const go=p=>{setPage(p);nav('/admin?tab='+p,{replace:true})};
 if(profile?.role!=='admin')return <div className="admin-denied"><i className="bi bi-shield-x"/><h1>Admin access required</h1><p>This account does not have administrator permissions.</p></div>;
 return <div className="admin-console"><AdminNav page={page} setPage={go}/><main className="admin-workspace">{loading?<div className="admin-loading"><div className="loading-mark">TAMP.</div><p>Preparing control center…</p></div>:page==='overview'?<Overview data={data} onRefresh={load}/>:page==='students'?<Students data={data}/>:page==='enrollments'?<Enrollments data={data}/>:page==='assignments'?<Assignments data={data}/>:page==='courses'?<Courses data={data}/>:page==='instructors'?<Instructors data={data}/>:page==='complaints'?<Complaints data={data}/>:page==='activity'?<Activity data={data}/>:page==='notifications'?<NotificationsPage data={data}/>:page==='sales'?<Sales data={data}/>:page==='admins'?<Admins profile={profile}/>:<Profile profile={profile}/>}</main></div>
}
